/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci400assignment.gui;

/**
 *
 * @author hamed
 */
public class SettingsPanel
  extends javax.swing.JPanel
{

    /**
     * Creates new form Settings
     */
    public SettingsPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jCheckBox4 = new javax.swing.JCheckBox();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox1.setName("settingsCheckbox");
        checkBox2 = new javax.swing.JCheckBox();
        checkBox2.setName("settingsCheckbox");
        checkBox4 = new javax.swing.JCheckBox();
        checkBox4.setName("settingsCheckbox");
        checkBox5 = new javax.swing.JCheckBox();
        checkBox5.setName("settingsCheckbox");
        checkBox3 = new javax.swing.JCheckBox();
        checkBox3.setName("settingsCheckbox");
        autoFetch = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkBox7 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        checkBox6 = new javax.swing.JCheckBox();
        sortBy = new javax.swing.JComboBox();
        sortIn = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        addAccount = new javax.swing.JButton();
        removeAccount = new javax.swing.JButton();
        createPlaylist = new javax.swing.JButton();
        removePlaylist = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        accountsTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        playListTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        autoDownloadTable = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        folderLocation = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        soundDriver = new javax.swing.JComboBox();

        jCheckBox4.setText("Enable auto-download");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
          new Object[][]{
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
          },
          new String[]{
              "Title 1", "Title 2", "Title 3", "Title 4"
          }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("General");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Playback");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Accounts");

        checkBox1.setSelected(true);
        checkBox1.setText("Check for new software updates automatically");
        checkBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox1ActionPerformed(evt);
            }
        });

        checkBox2.setSelected(true);
        checkBox2.setText("Start the program on system startup");
        checkBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox2ActionPerformed(evt);
            }
        });

        checkBox4.setText("Sort Home page content");
        checkBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox4ActionPerformed(evt);
            }
        });

        checkBox5.setText("Pause video playback when minimized");
        checkBox5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox5ActionPerformed(evt);
            }
        });

        checkBox3.setText("Automatically fetch new content every");
        checkBox3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox3ActionPerformed(evt);
            }
        });

        autoFetch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        autoFetch.setEnabled(false);

        jLabel5.setText("minute(s)");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("disabled: sorts by date & time in descending order");

        jLabel7.setText("by");

        jLabel8.setText("in");

        jLabel9.setText("order");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText(
          "the program can automatically download new posts, articles,");

        checkBox7.setText("Enable auto-download");
        checkBox7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkBox7ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.
          setText("images, audios and videos from the specified account.");

        checkBox6.setText("Pause now playing music when a video is played");

        sortBy.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
            "popularity", "date & time"}));
        sortBy.setEnabled(false);

        sortIn.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
            "descending", "ascending"}));
        sortIn.setEnabled(false);

        jLabel13.setText("Playlist Manager");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText(
          "Internet Accounts sets up your accounts to use with this program.");

        addAccount.setText("Add");

        removeAccount.setText("Remove");

        createPlaylist.setText("Create");

        removePlaylist.setText("Remove");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton6.setText("Cancel");

        jButton7.setText("Apply");

        jButton8.setText("Okay");

        accountsTable.setModel(new javax.swing.table.DefaultTableModel(
          new Object[][]{
              {new Boolean(false), "Facebook", "nathan21@facebook.com",
                  "connected"},
              {null, "Youtube", "nathan.beats@gmail.com", "connected"},
              {null, "SoundCloud", "nathan21@facebook.com", "error"},
              {null, "Twitter", "@nathan21", "connected"}
          },
          new String[]{
              "Enabled", "Account", "Signed-in as", "Status"
          }
        )
        {
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.String.class,
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(accountsTable);
        if(accountsTable.getColumnModel().getColumnCount() > 0) {
            accountsTable.getColumnModel().getColumn(0).setResizable(false);
            accountsTable.getColumnModel().getColumn(0).setPreferredWidth(240);
            accountsTable.getColumnModel().getColumn(1).setResizable(false);
            accountsTable.getColumnModel().getColumn(1).setPreferredWidth(450);
            accountsTable.getColumnModel().getColumn(2).setResizable(false);
            accountsTable.getColumnModel().getColumn(2).setPreferredWidth(650);
            accountsTable.getColumnModel().getColumn(3).setPreferredWidth(400);
        }

        playListTable.setModel(new javax.swing.table.DefaultTableModel(
          new Object[][]{
              {null, null, null},
              {null, null, null},
              {null, null, null},
              {null, null, null}
          },
          new String[]{
              "Playlist", "Date Modified", "Duration"
          }
        )
        {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit[columnIndex];
            }
        });
        jScrollPane4.setViewportView(playListTable);
        if(playListTable.getColumnModel().getColumnCount() > 0) {
            playListTable.getColumnModel().getColumn(0).setResizable(false);
            playListTable.getColumnModel().getColumn(1).setResizable(false);
            playListTable.getColumnModel().getColumn(2).setResizable(false);
        }

        autoDownloadTable.setModel(new javax.swing.table.DefaultTableModel(
          new Object[][]{
              {null, "Facebook"},
              {null, "Youtube"},
              {null, "SoundCloud"},
              {null, "Twitter"}
          },
          new String[]{
              "Enabled", "Account"
          }
        )
        {
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                true, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit[columnIndex];
            }
        });
        autoDownloadTable.setCursor(new java.awt.Cursor(
          java.awt.Cursor.DEFAULT_CURSOR));
        autoDownloadTable.setEditingColumn(0);
        autoDownloadTable.setEditingRow(0);
        autoDownloadTable.setEnabled(false);
        autoDownloadTable.setOpaque(false);
        jScrollPane5.setViewportView(autoDownloadTable);
        if(autoDownloadTable.getColumnModel().getColumnCount() > 0) {
            autoDownloadTable.getColumnModel().getColumn(0).setPreferredWidth(
              200);
            autoDownloadTable.getColumnModel().getColumn(1).setResizable(false);
            autoDownloadTable.getColumnModel().getColumn(1).setPreferredWidth(
              1000);
        }

        jButton9.setText("Change");

        folderLocation.setText("C:\\Users\\nathan\\Musics\\");

        jLabel16.setText("Media folder location");

        jLabel12.setText("Select a device for sound output");

        soundDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
            "Internal Speakers", "Digital Output"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createParallelGroup(
                      javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4,
                      javax.swing.GroupLayout.PREFERRED_SIZE, 335,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jLabel16)
                      .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(folderLocation,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jButton9,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jLabel12)
                      .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(soundDriver,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 175,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(createPlaylist)
                      .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(removePlaylist)))
                  .addComponent(jLabel3)
                  .addComponent(checkBox6)
                  .addComponent(checkBox5)
                  .addComponent(jLabel13))
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2,
                  javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                  javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel4)
                      .addGroup(layout.createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14)
                        .addGroup(layout.createSequentialGroup()
                          .addComponent(addAccount)
                          .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(removeAccount))
                        .addGroup(layout.createSequentialGroup()
                          .addComponent(jButton8)
                          .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jButton6)
                          .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addComponent(jButton7)))))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jScrollPane3,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                        Short.MAX_VALUE)
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                        .addComponent(checkBox7)
                        .addGap(214, 214, 214))
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jLabel11)
                          .addComponent(jLabel10))
                        .addGap(10, 10, 10))
                      .addComponent(jScrollPane5,
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 347,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSeparator1)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel2)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBox3)
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autoFetch,
                          javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                          javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                      .addComponent(checkBox4)
                      .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jLabel6)
                          .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED).
                            addComponent(sortBy,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED).
                            addComponent(jLabel8)
                            .addGap(4, 4, 4)
                            .addComponent(sortIn,
                              javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED).
                            addComponent(jLabel9))))
                      .addComponent(checkBox1)
                      .addComponent(checkBox2))
                    .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())))
        );
        layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(checkBox1)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox2)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(checkBox3)
                  .addComponent(autoFetch,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel5))
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox4)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel8)
                  .addComponent(jLabel9)
                  .addComponent(sortBy, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(sortIn, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel7)))
              .addGroup(layout.createSequentialGroup()
                .addComponent(checkBox7)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane5,
                  javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                  javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              15, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
              10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                  14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3,
                  javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                  javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(addAccount)
                  .addComponent(removeAccount))
                .addPreferredGap(
                  javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                  javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jButton8,
                    javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createParallelGroup(
                      javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSeparator2,
                    javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(checkBox5)
                    .addGap(1, 1, 1)
                    .addComponent(checkBox6)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(jLabel16)
                      .addComponent(folderLocation,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jButton9))
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(soundDriver,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jLabel12))
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel13)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4,
                      javax.swing.GroupLayout.PREFERRED_SIZE, 68,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(removePlaylist)
                      .addComponent(createPlaylist))))
                .addGap(0, 5, Short.MAX_VALUE)))
            .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBox1ActionPerformed
    {//GEN-HEADEREND:event_checkBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox1ActionPerformed

    private void checkBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBox2ActionPerformed
    {//GEN-HEADEREND:event_checkBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox2ActionPerformed

    private void checkBox4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBox4ActionPerformed
    {//GEN-HEADEREND:event_checkBox4ActionPerformed
        if(checkBox4.isSelected()) {
            sortBy.setEnabled(true);
            sortIn.setEnabled(true);
        } else {
            sortBy.setEnabled(false);
            sortIn.setEnabled(false);
        }
    }//GEN-LAST:event_checkBox4ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox4ActionPerformed
    {//GEN-HEADEREND:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void checkBox5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBox5ActionPerformed
    {//GEN-HEADEREND:event_checkBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox5ActionPerformed

    private void checkBox3ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_checkBox3ActionPerformed
        if(checkBox3.isSelected()) {
            autoFetch.setEnabled(true);
        } else {
            autoFetch.setEnabled(false);
        }
    }//GEN-LAST:event_checkBox3ActionPerformed

    private void checkBox7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkBox7ActionPerformed
    {//GEN-HEADEREND:event_checkBox7ActionPerformed
        if(checkBox7.isSelected()) {
            autoDownloadTable.setEnabled(true);
        } else {
            autoDownloadTable.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountsTable;
    private javax.swing.JButton addAccount;
    private javax.swing.JTable autoDownloadTable;
    private javax.swing.JSpinner autoFetch;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JCheckBox checkBox4;
    private javax.swing.JCheckBox checkBox5;
    private javax.swing.JCheckBox checkBox6;
    private javax.swing.JCheckBox checkBox7;
    private javax.swing.JButton createPlaylist;
    private javax.swing.JTextField folderLocation;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable playListTable;
    private javax.swing.JButton removeAccount;
    private javax.swing.JButton removePlaylist;
    private javax.swing.JComboBox sortBy;
    private javax.swing.JComboBox sortIn;
    private javax.swing.JComboBox soundDriver;
    // End of variables declaration//GEN-END:variables
}
