/*
 * Curtin University - Machine Perception 400 - Assignment
 * Group 11 - 2014S2
 */
package hci400assignment.gui.minimal;

import hci400assignment.ApplicationCore;
import hci400assignment.gui.GUIUtil;
import hci400assignment.gui.ImagePanel;
import hci400assignment.gui.ItemCard;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JViewport;

/**
 *
 * @author Declan White
 */
public class MinimalFocusPanel
  extends ItemCard
  implements ComponentListener
{

    /**
     * Creates new form MinimalFocusPanel
     */
    public MinimalFocusPanel()
    {
        initComponents();
        addComponentListener(this);
        
        try {
            ((ImagePanel)contentContainer).setImage(ImageIO.read(
              MinimalRootPanel.class.getResourceAsStream(
                "/hci400assignment/resources/bg.png"
              )
            ));
            ((ImagePanel)contentContainer).setMode(ImagePanel.Mode.TILE);
            
        } catch(IOException ex) {
            System.err.println("Could not load background");
            ex.printStackTrace(System.err);
        }
        
        contentScrollPane.getVerticalScrollBar().setUnitIncrement(24);
    }
    
    @Override
    protected void updateContent()
    {
        titleLabel.setText(item.getTitle());
        contentTextPane.setContentType("text/html");
        contentTextPane.setText(item.getContent());
        GUIUtil.revalidate(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        headerBar = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        titleBackground = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        contentContainer = new ImagePanel();
        leftPadding = new javax.swing.JPanel();
        contentBackground = new javax.swing.JPanel();
        contentScrollPane = new javax.swing.JScrollPane();
        contentTextPane = new javax.swing.JTextPane();
        rightPadding = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 6), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true)));
        setName("control_bar_bg"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        headerBar.setLayout(new java.awt.GridBagLayout());

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci400assignment/resources/icons-small/rewind.png"))); // NOI18N
        backButton.setText("  Back");
        backButton.setToolTipText("");
        backButton.setName("control_bar_button"); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        headerBar.add(backButton, gridBagConstraints);

        titleBackground.setName("minimal_preview_title_bg"); // NOI18N
        titleBackground.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setText("!!!");
        titleLabel.setName("minimal_preview_title"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 21, 3, 9);
        titleBackground.add(titleLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        headerBar.add(titleBackground, gridBagConstraints);

        add(headerBar, java.awt.BorderLayout.NORTH);

        contentContainer.setLayout(new java.awt.GridBagLayout());

        leftPadding.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout leftPaddingLayout = new javax.swing.GroupLayout(leftPadding);
        leftPadding.setLayout(leftPaddingLayout);
        leftPaddingLayout.setHorizontalGroup(
            leftPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftPaddingLayout.setVerticalGroup(
            leftPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        gridBagConstraints.weighty = 1.0;
        contentContainer.add(leftPadding, gridBagConstraints);

        contentBackground.setName("focus_bg"); // NOI18N
        contentBackground.setLayout(new java.awt.BorderLayout());

        contentScrollPane.setViewportView(contentTextPane);

        contentBackground.add(contentScrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        contentContainer.add(contentBackground, gridBagConstraints);

        rightPadding.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout rightPaddingLayout = new javax.swing.GroupLayout(rightPadding);
        rightPadding.setLayout(rightPaddingLayout);
        rightPaddingLayout.setHorizontalGroup(
            rightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rightPaddingLayout.setVerticalGroup(
            rightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.15;
        gridBagConstraints.weighty = 1.0;
        contentContainer.add(rightPadding, gridBagConstraints);

        add(contentContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        ApplicationCore.getInstance().goBack();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel contentBackground;
    private javax.swing.JPanel contentContainer;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JTextPane contentTextPane;
    private javax.swing.JPanel headerBar;
    private javax.swing.JPanel leftPadding;
    private javax.swing.JPanel rightPadding;
    private javax.swing.JPanel titleBackground;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent ce)
    {
        if(contentScrollPane == null || contentContainer == null) {
            return;
        }
        JViewport viewport = contentScrollPane.getViewport();
        if(viewport != null) {
            contentContainer.setPreferredSize(viewport.getSize());
        }
    }
    
    @Override
    public void componentMoved(ComponentEvent ce)
    {
        // 
    }
    
    @Override
    public void componentShown(ComponentEvent ce)
    {
        // 
    }
    
    @Override
    public void componentHidden(ComponentEvent ce)
    {
        // 
    }
}
