/*
 * Curtin University - Machine Perception 400 - Assignment
 * Group 11 - 2014S2
 */
package hci400assignment.gui.minimal;

import hci400assignment.ApplicationCore;

import hci400assignment.gui.Card;
import hci400assignment.gui.CardGrid;
import hci400assignment.gui.ImagePanel;
import hci400assignment.model.Item;
import java.util.List;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import javax.swing.JOptionPane;

/**
 * MINIMAL!
 *
 * @author Deco
 */
public class RootPanel
  extends javax.swing.JPanel
{

    private List<PreviewCard> articleCardList;
    private final CardGrid cardGrid;

    /**
     * Creates new form RootPanel
     */
    public RootPanel() throws IOException
    {
        initComponents();

        articleCardList = new ArrayList<PreviewCard>();

        double aspectRatio = 0.74;
        double imageHeightPc = 0.61;
        int cardWidthMin = 346;
        for(int i = 0; i < 20; i++) {
            PreviewCard c = new PreviewCard(new Item());
            articleCardList.add(c);
        }

        final List<PreviewCard> modelCardList = articleCardList;
        cardGrid = new CardGrid(new ListModel()
        {

            @Override
            public int getSize()
            {
                return modelCardList.size();
            }

            @Override
            public Card getElementAt(int i)
            {
                return modelCardList.get(i);
            }

            @Override
            public void addListDataListener(ListDataListener ll)
            {
                // 
            }

            @Override
            public void removeListDataListener(ListDataListener ll)
            {
                // 
            }
        });

        cardGrid.setBackgroundPanel(new ImagePanel(
          ImageIO.read(
            RootPanel.class.getResourceAsStream(
              "/hci400assignment/resources/bg.png"
            )
          ),
          ImagePanel.Mode.TILE
        ));
        cardGrid.setCardWidthMin(cardWidthMin);

        contentRootPanel.add(cardGrid, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        navBar = new hci400assignment.gui.minimal.NavBar();
        contentRootPanel = new javax.swing.JPanel();
        controlsBar1 = new hci400assignment.gui.ControlBar();

        setLayout(new java.awt.BorderLayout());
        add(navBar, java.awt.BorderLayout.NORTH);

        contentRootPanel.setLayout(new java.awt.BorderLayout());
        add(contentRootPanel, java.awt.BorderLayout.CENTER);
        add(controlsBar1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentRootPanel;
    private hci400assignment.gui.ControlBar controlsBar1;
    private hci400assignment.gui.minimal.NavBar navBar;
    // End of variables declaration//GEN-END:variables
}
