/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutBox.java
 *
 * Created on 15/10/2014, 2:52:14 PM
 */
package hci400assignment;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import org.jdesktop.application.Action;

/**
 *
 * @author 16152939
 */
public class AboutBox extends javax.swing.JPanel {

    /** Creates new form AboutBox */
    public AboutBox() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        content = new javax.swing.JLabel();
        content1 = new javax.swing.JLabel();
        background = new FancyLabel();

        setName("aboutPanel"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        content.setText("<html><center> This program was created by Team Placeholder<br> Made in Mid 2014. <br> All rights reserved.<br>  </center></html>"); // NOI18N
        content.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        content.setName("content"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(content, gridBagConstraints);

        content1.setText("<html> About Placeholder </html>"); // NOI18N
        content1.setName("content1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        add(content1, gridBagConstraints);

        background.setBackground(new java.awt.Color(225, 144, 64));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci400assignment/resources/about.png"))); // NOI18N
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.setName("background"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(background, gridBagConstraints);

        getAccessibleContext().setAccessibleName("aboutPanel");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel content;
    private javax.swing.JLabel content1;
    // End of variables declaration//GEN-END:variables

    public static class FancyLabel
            extends JLabel
            implements ComponentListener {

        public FancyLabel() {
            super();

            addComponentListener(this);
        }

        public void componentResized(ComponentEvent e) {
            
            ImageIcon icon = (ImageIcon) getIcon();

            //System.out.println(getWidth() + " " + getHeight());
            Image i = (new javax.swing.ImageIcon(getClass().getResource("/hci400assignment/resources/about.png"))).getImage().getScaledInstance(getWidth(), getHeight(), 0);
            icon.setImage(i);
            setIcon(icon);
            repaint();
        }

        public void componentMoved(ComponentEvent e) {
            //
        }

        public void componentShown(ComponentEvent e) {
            //
        }

        public void componentHidden(ComponentEvent e) {
            //
        }
    }

    
}
